### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ManOfStory** [gaoxiangjun/Mani-GS#2]
Has anyone who met this error?
When I tried on a 3090 machine, there is no error, while when I tried on a 4090 machine, "RuntimeError: CUDA error: an illegal memory access was encountered" happens.
![image](https://github.com/gaoxiangjun/Mani-GS/assets/67816242/6b18f9f6-0dc9-46d4-8907-e0111544a1d3)
thank you.

**Comment by gaoxiangjun** [comment]
Bug Fix of Poisson Mesh cleaning.
