### ISSUE TITLE
preprocessing of data

### ISSUE THREAD

**Issue by ManOfStory** [gaoxiangjun/Mani-GS#3]
May I ask how can I get the "mesh_neus_decimate.ply", "mesh_poi_clean.ply", "mesh_mc_30K.ply" and "mesh_K.ply"？Thank you!

**Comment by gaoxiangjun** [comment]
https://drive.google.com/file/d/1Ox0dhiKMfiLc5Rly01h0viJVCd2rHtcr/view?usp=drive_link

Please download from the Link here, also provided in README.md
