### ISSUE TITLE
densification_bind used before assignment

### ISSUE THREAD

**Issue by ManOfStory** [gaoxiangjun/Mani-GS#4]
When the mode is not "bind" or "bind_mesh_adapt", The densification_bind used before assignment. Is the code here necessary？
'''
if (iteration < opt.densify_until_iter) and densification_bind:
                # Keep track of max radii in image-space for pruning
                gaussians.max_radii2D[visibility_filter] = torch.max(gaussians.max_radii2D[visibility_filter],
                                                                     radii[visibility_filter])
                gaussians.add_densification_stats(viewspace_point_tensor, visibility_filter)

                if iteration > opt.densify_from_iter and iteration % opt.densification_interval == 0:
                    size_threshold = 20 if iteration > opt.opacity_reset_interval else None
                    min_opacity = 0.005 # 0.005
                    gaussians.densify_and_prune(opt.densify_grad_threshold, min_opacity, scene.cameras_extent, size_threshold,
                                                opt.densify_grad_normal_threshold)

                if iteration % opt.opacity_reset_interval == 0 or (
                        dataset.white_background and iteration == opt.densify_from_iter):
                    gaussians.reset_opacity()

'''
when I deleted "and densification_bind" to run this code, the training will fail to train the model when the iteration is set to 1000 or larger. How can I solve this, thank you.

**Comment by lziiid** [comment]
Same problem. Hope somebody help :(

**Comment by Mila-Charlie** [comment]
I also encountered the same problem, have you solved it?

**Comment by ManOfStory** [comment]
> I also encountered the same problem, have you solved it?

I simply removed opt.densification_interval and it runs successfully.

**Comment by gaoxiangjun** [comment]
Bug Fixed in train.py.
