### ISSUE TITLE
'GaussianModel' object has no attribute 'anchor scale'

### ISSUE THREAD

**Issue by Mila-Charlie** [gaoxiangjun/Mani-GS#5]
When I run the code, it reminds me that 'GaussianModel' object has no attribute 'anchor scale' when it runs to 2499 times. How can I solve this problem?

![2024-09-09 14-49-36 的屏幕截图](https://github.com/user-attachments/assets/aaa1fc95-c981-4491-a58f-9d547bafceba)

**Comment by zvict** [comment]
I have the same issue when running stage 1 on my own dataset from scratch, does it require a pre-trained 3DGS model?

**Comment by gaoxiangjun** [comment]
Bug Fixed.
